baseURL = "/"
languageCode = "en-us"
theme = "hyde"
title = "Gabe"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/gabegm/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gabegm/"},
      {Name = "Twitter", URL = "https://twitter.com/itsgabegm/"}
  ]

[params]
  description = "Data Scientist"
  themeColor = "theme-base-0d"
  layoutReverse = false
  disqusShortname = "spf13"
  googleAnalytics = ""
