baseURL = "www.gabriel.gaucimaistre.com"
languageCode = "en-us"
theme = "hyde"
title = "Gabe"

[Menus]
  main = [
      {Name = "CV", URL = "/pdf/resume-gabriel-gauci-maistre.pdf"},
      {Name = "Github", URL = "https://github.com/gabegm/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gabegm/"},
      {Name = "Twitter", URL = "https://twitter.com/itsgabegm/"}
  ]

[params]
  AuthorName = "Gabriel Gauci Maistre"
  GitHubUser = "gabegm"
  description = "Data Scientist"
  themeColor = "theme-base-0g"
  layoutReverse = false
  disqusShortname = ""
  googleAnalytics = ""


[permalinks]
  posts = "/:year/:month/:title/"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
