baseURL = "https://gabriel.gaucimaistre.com/"
languageCode = "en-us"
theme = "hyde"
title = "Gabe"
summary = "Gabriel Gauci Maistre"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/gabegm/"},
      {Name = "Twitter", URL = "https://twitter.com/itsgabegm/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gabegm/"}
  ]

[params]
  AuthorName = "Gabriel Gauci Maistre"
  GitHubUser = "gabegm"
  description = "I have opinions and make people read them."
  jobTitle = "Data Scientist"
  images = ["/images/avatar.jpg"]
  themeColor = "theme-base-0g"
  layoutReverse = false
  disqusShortname = ""
  googleAnalytics = ""


[permalinks]
  posts = "/:year/:month/:title/"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]

[taxonomies]
  series = "series"
  tags = "tags"

[markup]
  [markup.goldmark]
     [markup.goldmark.renderer]
        unsafe = true