baseURL = "www.gabriel.gaucimaistre.com"
languageCode = "en-us"
theme = "hyde"
title = "Gabe"

[Menus]
  main = [
      {Name = "CV", URL = "/pdf/resume-gabriel-gauci-maistre.pdf"},
      {Name = "Github", URL = "https://github.com/gabegm/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gabegm/"},
      {Name = "Twitter", URL = "https://twitter.com/itsgabegm/"}
  ]

[params]
  description = "Data Scientist"
  themeColor = "theme-base-0g"
  layoutReverse = false
  disqusShortname = ""
  googleAnalytics = ""
